import os
from dotenv import load_dotenv

load_dotenv()

ARK_API_KEY = os.getenv("ARK_API_KEY", "")
ARK_ENDPOINT_ID = os.getenv("ARK_ENDPOINT_ID", "")
ARK_ENDPOINT_ID_SEEDREAM_5_LITE = os.getenv("ARK_ENDPOINT_ID_SEEDREAM_5_LITE", "")
ARK_ANALYSIS_ENDPOINT_ID = os.getenv("ARK_ANALYSIS_ENDPOINT_ID", "")
ARK_ANALYSIS_ENDPOINT_ID_SEED_2_MINI = os.getenv("ARK_ANALYSIS_ENDPOINT_ID_SEED_2_MINI", "")
ARK_ANALYSIS_ENDPOINT_ID_SEED_2_PRO = os.getenv("ARK_ANALYSIS_ENDPOINT_ID_SEED_2_PRO", "")
